
IDF_TOOLS_PATH=/Users/davidm/code/paperframe/esp32/eso_tools
IDF_PATH=/Users/davidm/code/paperframe/esp32/esp-idf
export IDF_TOOLS_PATH
export IDF_PATH

all: 
	echo wtf

esp-idf:
	git clone -b v4.3.1 --recursive https://github.com/espressif/esp-idf.git

install: | esp-idf
	./esp-idf/install.sh





